// 'use client';

import Head from 'next/head';
import Header from './components/Header';
import { useAuth } from '@/hooks/useAuth';

export default function Home() {
  const { logout, loading } = useAuth();

  if (loading) return null;

  return (
    <>
      <Head>
        <title>Staff Manage App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-red-50'>
        <Header />
        <div>Hey this is home page</div>
        <button onClick={logout}>Log out</button>
      </main>
    </>
  );
}
