import Head from 'next/head';
import Header from '../components/header/Header';
import { useAuth } from '@/hooks/useAuth';
import Sidebar from '@/components/Sidebar';
import HomeContent from '@/components/HomeContent';
import { useRecoilValue, useSetRecoilState } from 'recoil';
import { adminState } from '@/recoil/adminAtom';
import { useQuery } from '@apollo/client';
import { GET_SINGLE_USER } from '@/graphql/queries/user';
import { drawerState } from '@/recoil/drawerOpen';
import { Toaster } from 'react-hot-toast';

export default function Home() {
  const { loading, user } = useAuth();
  const { data } = useQuery(GET_SINGLE_USER, {
    variables: { email: user?.email },
    pollInterval: 500,
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-and-network',
  });
  const setIsAdmin = useSetRecoilState(adminState);
  const openSideBar = useRecoilValue(drawerState);

  if (loading) return null;

  if (data?.getSingleUser?.role === 'admin') {
    setIsAdmin(true);
  }
  if (!user) setIsAdmin(false);

  return (
    <>
      <Head>
        <title>Staff Manage App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-row'>
        <Toaster />
        {openSideBar && <Sidebar />}
        <div className='flex flex-col w-full'>
          <Header />
          <HomeContent />
        </div>
      </main>
    </>
  );
}
