// 'use client';

import Head from 'next/head';
import Header from '../components/header/Header';
import { useAuth } from '@/hooks/useAuth';
import Sidebar from '@/components/Sidebar';
import MainContent from '@/components/MainContent';

export default function Home() {
  const { loading } = useAuth();

  if (loading) return null;

  return (
    <>
      <Head>
        <title>Staff Manage App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-row'>
        <Sidebar />
        <div className='flex flex-col w-full'>
          <Header />
          <MainContent />
        </div>
      </main>
    </>
  );
}
